name: Update Version and Create Release Branch (reusable)

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: "リリース種別"
        required: true
        type: choice
        default: patch
        options:
          - major
          - minor
          - patch

jobs:
  call-common-release:
    uses: Seika139/.github/.github/workflows/update-version.yml@main
    with:
      version_bump: ${{ inputs.version_bump }}
    secrets: inherit
