name: Qualify Code (reusable)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  call-common-uv-qualify:
    strategy:
      fail-fast: false # いずれかのバージョンで失敗しても他のバージョンの実行を継続する
      matrix:
        # 呼び出し側でテストしたい Python バージョンを指定する
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    uses: Seika139/.github/.github/workflows/uv-qualify.yml@main
    with:
      python-version: ${{ matrix.python-version }}
      # dotenvx を使う場合の例:
      # dotenvx-env-file: ".env.production"
    secrets: inherit
    # dotenvx を使う場合の例:
    # secrets:
    #   DOTENV_PRIVATE_KEY: ${{ secrets.DOTENV_PRIVATE_KEY }}
